// Marketplace Data
export const AGENT_PRODUCTS = [
  {
    id: 'studex-research-agent',
    name: 'Studex Research Agent',
    tagline: 'Know everything. Miss nothing.',
    category: 'Intelligence',
    color: '#4d9fff',
    based_on: 'Multi-agent orchestration (crewAI architecture)',
    base_price: 2500,
    price_suffix: '/month',
    pricing_note: 'Includes DeepSeek R2 inference — 1/10th GPT-4 cost',
    icon: '🔬',
    description: 'An autonomous research agent that scans 9 countries every night, tracks your competitors in real time, monitors market movements, and delivers actionable intelligence briefings every morning. Built on a multi-agent architecture — one agent scrapes, one analyses, one synthesises, one presents.',
    what_you_get: [
      'Nightly 9-country scan (South Africa, Nigeria, Ghana, Kenya, Egypt, India, China, USA, Brazil)',
      'Competitor tracking — monitors 20 competitor URLs automatically',
      'Market signal alerts — Telegram/WhatsApp when something important happens',
      'Daily intelligence briefing at 6am — delivered to your inbox',
      'Full research archive — queryable knowledge base',
      'Custom research requests — ask anything, get a cited answer',
      'Real-time web search on demand',
    ],
    use_cases: ['Market intelligence', 'Competitor monitoring', 'Demand research', 'Partner scouting'],
    vm_isolated: true,
    vm_note: 'Runs in isolated VM — your research data never mixes with other clients',
    badge: 'BESTSELLER',
    featured: true,
    screenshots: 1,
  },
  {
    id: 'studex-builder-agent',
    name: 'Studex Builder Agent',
    tagline: 'Ship products while you sleep.',
    category: 'Engineering',
    color: '#00ff88',
    based_on: 'Manus/CrewAI architecture + Codex',
    base_price: 4500,
    price_suffix: '/month',
    pricing_note: 'Includes Claude Code + QwenPaw local coding — near-zero API cost',
    icon: '🏗️',
    description: 'The Builder Agent turns ideas into deployed products. Give it a voice note, a Figma link, or a spec document — it writes the PRD, builds the code, reviews every PR with CodeRabbit, and deploys to production. Ships one small product every night automatically.',
    what_you_get: [
      'PRD generation from voice note, link, or text',
      'Automated spec → code → deploy pipeline',
      'CodeRabbit PR review on every change',
      'Nightly builds — ships something every 24 hours',
      'GitHub integration — full version control',
      'Vercel/AWS deployment included',
      'Screenshot verification of every deployment',
    ],
    use_cases: ['MVP building', 'Internal tools', 'Prototypes', 'Iterating on ideas'],
    vm_isolated: true,
    vm_note: 'Runs in dedicated Dev VM — code is private, builds are isolated',
    badge: 'NEW',
    featured: true,
    screenshots: 1,
  },
  {
    id: 'studex-social-agent',
    name: 'Studex Social Agent',
    tagline: 'Your brand. Every day. Everywhere.',
    category: 'Marketing',
    color: '#ff4d88',
    based_on: 'Multi-agent content pipeline + last30days intelligence',
    base_price: 1800,
    price_suffix: '/month',
    pricing_note: 'Generates 60 pieces of content per month',
    icon: '📱',
    description: 'Generates and schedules a month of social content in 30 minutes. Uses real-time market intelligence to make every post relevant. Connects to LinkedIn, Twitter/X, Instagram, and Facebook. Posts automatically. Responds to comments. Tracks engagement.',
    what_you_get: [
      '60 posts per month across all platforms (20 per platform)',
      'Content calendar generated automatically',
      'Auto-posting with optimal timing',
      'Comment responses and engagement',
      'Weekly performance report',
      'Trending topic integration — posts what\'s relevant now',
      'Custom brand voice training',
    ],
    use_cases: ['Content marketing', 'Brand building', 'Thought leadership', 'Social selling'],
    vm_isolated: true,
    vm_note: 'Runs in isolated VM — your brand data and credentials are private',
    badge: null,
    featured: false,
    screenshots: 1,
  },
  {
    id: 'studex-email-agent',
    name: 'Studex Email Agent',
    tagline: 'Every lead followed up. Every reply in minutes.',
    category: 'Sales',
    color: '#ffd700',
    based_on: 'cold-email + email-sequence skills stack',
    base_price: 2200,
    price_suffix: '/month',
    pricing_note: 'Unlimited email sends within fair-use policy',
    icon: '📧',
    description: 'Handles your entire email sales pipeline. Writes personalised cold outreach, follows up at the right time, responds to inbound leads within minutes, and moves deals through your pipeline automatically. Integrates with Gmail, HubSpot, and any CRM.',
    what_you_get: [
      'Personalised cold email campaigns — writes each email individually',
      'Automated follow-up sequences — 5-touch nurture',
      'Lead response within 2 minutes — instant reply to enquiries',
      'CRM pipeline updates — automatically logs every touchpoint',
      'Email warmup and deliverability management',
      'Unsubscribe and bounce handling',
      'Reply parsing and action extraction',
    ],
    use_cases: ['Lead generation', 'Outbound sales', 'Client onboarding', 'Customer support'],
    vm_isolated: true,
    vm_note: 'Runs in isolated VM — your email credentials and lead data are secure',
    badge: null,
    featured: false,
    screenshots: 1,
  },
  {
    id: 'studex-seo-agent',
    name: 'Studex SEO Agent',
    tagline: 'Rank. Monitor. Dominate.',
    category: 'Marketing',
    color: '#a855f7',
    based_on: 'ai-seo + seo-audit + seo-geo skills stack',
    base_price: 2000,
    price_suffix: '/month',
    pricing_note: 'Includes weekly technical audit + content optimisation',
    icon: '🎯',
    description: 'Full-stack SEO agent. Runs technical audits every week, optimises your existing content, identifies keyword opportunities from real search data, and tracks your ranking position 24/7. Reports weekly with specific actions taken, not just data.',
    what_you_get: [
      'Weekly technical SEO audit (Core Web Vitals, crawl errors, indexation)',
      'Content gap analysis — what competitors rank for that you don\'t',
      'Keyword research from real search data — not generic tools',
      'Weekly ranking report with position changes',
      'Auto-optimise meta titles, descriptions, and headers',
      'Backlink monitoring and toxicity scoring',
      'GEO/AI Overview optimisation — get cited by ChatGPT and Perplexity',
    ],
    use_cases: ['SEO growth', 'Content strategy', 'AI search optimisation', 'Competitor outranking'],
    vm_isolated: true,
    vm_note: 'Runs in isolated VM — your SEO data is proprietary and private',
    badge: null,
    featured: false,
    screenshots: 1,
  },
  {
    id: 'studex-crm-agent',
    name: 'Studex CRM Agent',
    tagline: 'Your pipeline. Running itself.',
    category: 'Sales',
    color: '#06b6d4',
    based_on: 'Notion CRM + pipeline automation',
    base_price: 1500,
    price_suffix: '/month',
    pricing_note: 'No CRM software required — built on Notion',
    icon: '💼',
    description: 'Automates your entire sales pipeline. Logs every lead, follows up at the right moment, moves deals through stages, flags deal risks, and sends you a daily pipeline report every morning. Works with or without an existing CRM.',
    what_you_get: [
      'Lead capture from email, WhatsApp, web forms',
      'Automated lead scoring — focus on the deals most likely to close',
      'Follow-up reminders — sent at the perfect time',
      'Pipeline view dashboard — real-time deal status',
      'Weekly revenue forecast — what\'s closing this week/month',
      'Deal risk alerts — when a deal goes cold',
      'Revenue log — track every close with R values',
    ],
    use_cases: ['Pipeline management', 'Lead tracking', 'Revenue forecasting', 'Small business CRM'],
    vm_isolated: true,
    vm_note: 'Runs in isolated VM — your client data is private and POPIA-compliant',
    badge: null,
    featured: false,
    screenshots: 1,
  },
];

export const SKILLS_MARKETPLACE = [
  {
    id: 'cold-email-mastery',
    name: 'Cold Email Mastery',
    category: 'Sales & Outreach',
    color: '#ffd700',
    price: 299,
    price_type: 'one-time',
    icon: '📧',
    description: 'The complete cold email system. 50+ swipeable templates, personalisation framework, deliverability checklist, and the exact sequence Tumelo uses to get 30% reply rates.',
    skills_you_get: [
      '50+ cold email templates by industry and use case',
      'Personalisation framework — stand out in any inbox',
      'Email deliverability checklist — never land in spam',
      '5-touch follow-up sequence templates',
      'Subject line swipe file — 200+ proven subject lines',
    ],
    badge: 'MOST POPULAR',
    rating: 4.9,
    students: 1847,
  },
  {
    id: 'ai-content-factory',
    name: 'AI Content Factory',
    category: 'Content & Marketing',
    color: '#ff4d88',
    price: 399,
    price_type: 'one-time',
    icon: '✍️',
    description: 'Build a content machine that generates a month of social posts, blog articles, and email newsletters in under 2 hours. Includes the exact workflow Tumelo uses for the Dark Factory social calendar.',
    skills_you_get: [
      '60 social posts per month generator',
      'Blog article outline generator',
      'Email newsletter template pack',
      'Content calendar system (Notion-based)',
      'Trending topic scanner — posts what\'s relevant now',
    ],
    badge: null,
    rating: 4.8,
    students: 934,
  },
  {
    id: 'market-intelligence-suite',
    name: 'Market Intelligence Suite',
    category: 'Research & Intelligence',
    color: '#4d9fff',
    price: 599,
    price_type: 'one-time',
    icon: '🔬',
    description: 'The last30days skill + competitor tracking + demand research framework. The exact system we use every night in the Dark Factory. Scan 9 countries, 50 competitors, and 200 signals — every morning automatically.',
    skills_you_get: [
      'last30days-skill — real-time market intelligence',
      '9-country scanning framework',
      '50-competitor tracker setup',
      'Demand signal detection — what people are asking for',
      'Opportunity radar dashboard',
    ],
    badge: 'ENTERPRISE',
    rating: 5.0,
    students: 312,
  },
  {
    id: 'agentic-engineering-stack',
    name: 'Agentic Engineering Stack',
    category: 'Engineering & Dev',
    color: '#00ff88',
    price: 899,
    price_type: 'one-time',
    icon: '🛠️',
    description: 'The gstack YC sprint process + 24 engineering workflows + spec-kit + Claude Code integration. Everything Tumelo uses to ship products in 48 hours with agents.',
    skills_you_get: [
      'gstack YC sprint framework — ship in sprints',
      '24 engineering workflows (TDD, security, performance)',
      'Spec-driven development with spec-kit',
      'Claude Code integration guide',
      'QwenPaw local multi-agent setup (zero API cost)',
    ],
    badge: 'FOR DEVELOPERS',
    rating: 4.9,
    students: 567,
  },
  {
    id: 'seo-ai-dominance',
    name: 'SEO + AI Search Dominance',
    category: 'Marketing & Growth',
    color: '#a855f7',
    price: 449,
    price_type: 'one-time',
    icon: '🏆',
    description: 'The complete SEO + GEO (Generative Engine Optimisation) system. Rank on Google AND get cited by ChatGPT, Perplexity, and Gemini. Includes the exact schema markup and content framework.',
    skills_you_get: [
      'Technical SEO audit framework',
      'Content optimisation for traditional SEO + AI search',
      'Schema markup builder (JSON-LD)',
      'GEO toolkit — get cited by AI assistants',
      'Weekly ranking tracker template',
    ],
    badge: null,
    rating: 4.7,
    students: 721,
  },
  {
    id: 'automation-blueprints',
    name: 'Automation Blueprints',
    category: 'Operations & Automation',
    color: '#f97316',
    price: 349,
    price_type: 'one-time',
    icon: '⚡',
    description: '12 n8n automation workflows that Tumelo runs in his own business. From lead capture to invoice sending, from social posting to revenue logging — automate everything in under 2 hours.',
    skills_you_get: [
      '12 n8n workflow templates',
      'Lead capture → CRM pipeline workflow',
      'Invoice generation workflow',
      'Social media auto-posting workflow',
      'Revenue logging to Notion workflow',
    ],
    badge: 'NEW',
    rating: 4.8,
    students: 445,
  },
];

export const VM_SANDBOX_REASONS = [
  {
    icon: '🔒',
    title: 'Complete Data Isolation',
    detail: 'Every agent runs in its own virtual machine. Your client data, credentials, and research never mix with another company\'s data. GDPR and POPIA compliant by architecture, not by policy.',
    color: '#00ff88',
  },
  {
    icon: '🛡️',
    title: 'Security Hardened by Default',
    detail: 'Each VM is firewalled, has its own credentials store, and operates with least-privilege access. Even if one agent is compromised, the blast radius is zero. Your other agents keep running.',
    color: '#4d9fff',
  },
  {
    icon: '⚡',
    title: 'Performance Guaranteed',
    detail: 'No shared compute. Your agent doesn\'t slow down when another client\'s agent spikes usage. The GPU cluster is yours while you\'re running. Dedicated resources. Predictable speed.',
    color: '#ffd700',
  },
  {
    icon: '🌍',
    title: 'POPIA-Compliant by Design',
    detail: 'South African data stays in South Africa. Our VMs run on SA infrastructure. No data crosses borders without explicit consent. We\'re SAHPRA-ready for pharma clients. B-BBEE Level 1 certified.',
    color: '#ff4d88',
  },
  {
    icon: '🔄',
    title: 'Agent Updates Without Downtime',
    detail: 'Update one agent\'s skills without touching any other agent. Roll back a bad update in 30 seconds. Each VM is independently versioned and snapshots are taken before every update.',
    color: '#a855f7',
  },
  {
    icon: '📊',
    title: 'Per-Agent Cost Attribution',
    detail: 'Know exactly how much each agent costs you. Each VM has its own resource meter. Track R per lead, R per post, R per product shipped. Optimise based on real data, not guesswork.',
    color: '#06b6d4',
  },
];
