// Tumelo Ramaphosa — Complete Profile Data
export const TUMELO_PROFILE = {
  name: 'Tumelo Ramaphosa',
  title: 'Founder & CEO — Studex Group',
  subtitle: '"SA\'s First Son" · Serial Entrepreneur · AI Operator',
  bio: `Tumelo Ramaphosa is the son of South African President Cyril Ramaphosa, and a serial entrepreneur building Africa's most ambitious AI-powered business ecosystem. From McDonald's to premium Wagyu, from cryptocurrency to cloud infrastructure, from AI agents to Russia-Africa trade — Tumelo has spent 11+ years at the intersection of technology, trade, and transformation.`,
  
  education: 'Hult International Business School · AWS Certified Cloud Practitioner (Youngest in Africa)',
  location: 'Johannesburg, South Africa · San Francisco, USA',
  social: { instagram: '87K followers', linkedin: 'CEO at Studex Group' },
  
  companies: [
    {
      name: 'StudEx Enterprise',
      founded: '2017',
      location: 'San Francisco, CA · Johannesburg, SA',
      sector: 'IT Consultancy · Cloud FinOps · AI Solutions',
      tagline: 'Africa\'s Cloud Cost Optimization Experts',
      status: 'ACTIVE',
      color: '#00ff88',
      website: 'studexgroup.com',
      description: `Official AWS + Google Cloud partner. StudEx Enterprise helps South African companies cut cloud waste by up to 35%. Partnered with Reserved.ai to deploy AI-powered cloud financial management across Africa — the first platform of its kind on the continent. Running proof-of-concept pilots with 6 SA enterprises.`,
      key_milestones: [
        { year: 2017, event: 'StudEx Enterprise founded in San Francisco, expanded to SA' },
        { year: 2018, event: 'ICO versus Venture Funding panel — Tumelo pitches at Sheppard Mullin, Palo Alto' },
        { year: 2019, event: 'Official AWS + Google Cloud partnership signed' },
        { year: 2020, event: 'ITWeb feature: "SA\'s First Son looks to cut cloud costs" — Tumelo launches cloud optimization mission' },
        { year: 2020, event: 'Partnership with Reserved.ai — AI cloud FinOps for Africa' },
        { year: 2020, event: 'Speaking at IV Forum Russia-Africa: "What\'s Next?"' },
        { year: 2025, event: 'Cloud Summit Africa: Partnerships with Google, AWS, Alibaba expanding' },
      ],
      ai_tools: ['Reserved.ai (AI FinOps)', 'AWS Cost Explorer', 'Google Cloud Billing API', 'Custom ML pipeline monitoring'],
      key_clients: '6 SA enterprises in PoC · Financial services · Retail · Logistics',
    },
    {
      name: 'Studex Meat',
      founded: '2011',
      location: 'Johannesburg, SA',
      sector: 'Premium Halaal Wagyu · Ankole Beef · Fine Dining Supply',
      tagline: 'South Africa\'s Finest Halaal Wagyu',
      status: 'ACTIVE',
      color: '#ff4d88',
      website: 'studexmeat.com',
      description: `Premium halal Wagyu beef producer and distributor. From fire-kissed, richly marbled steaks to whole carcass supply for SA's finest restaurants. 11+ years running. Now adding AI-powered supply chain optimization, cold chain monitoring, and computer vision quality control.`,
      key_milestones: [
        { year: 2011, event: 'Founded — from McDonald\'s employee to SA\'s premier Wagyu supplier' },
        { year: 2015, event: 'Expanded to full restaurant supply — 50+ fine dining clients' },
        { year: 2020, event: 'COVID pivot: online ordering + direct-to-consumer' },
        { year: 2023, event: '11 years of AI — Tumelo celebrates with AI-themed campaigns' },
        { year: 2024, event: 'Studex VIP Experience — exclusive wagyu events for 87K social followers' },
        { year: 2025, event: 'AI supply chain integration: computer vision quality grading — nTech Labs partnership' },
      ],
      ai_tools: ['nTech Labs Computer Vision (quality grading)', 'AI demand forecasting', 'Cold chain IoT monitoring'],
      key_clients: '50+ fine dining restaurants SA · Export to Africa · High net worth individuals',
    },
    {
      name: 'StudEx Wild Life',
      founded: '2017',
      location: 'Johannesburg, SA',
      sector: 'Conservation Technology · Blockchain · Cryptocurrency',
      tagline: 'Digital Stock Exchange for Animals',
      status: 'ACTIVE',
      color: '#ffd700',
      description: `First-of-its-kind digital platform using blockchain and cryptocurrency to enable global participation in wildlife conservation. "Virtual farmers" invest in animal conservation, generating returns while protecting habitats from poachers, predators, and disease. Uses tomorrow\'s technology to impact today\'s world.`,
      key_milestones: [
        { year: 2017, event: 'Launched as first blockchain wildlife conservation platform in SA' },
        { year: 2019, event: 'Featured in GQ SA: "Changing the nature of conservation"' },
        { year: 2021, event: 'Expanded to 5 conservation projects across Southern Africa' },
        { year: 2023, event: 'Tokenized assets on blockchain — new investor cohort' },
      ],
    },
    {
      name: 'StudEx Live',
      founded: '2019',
      location: 'Johannesburg, SA',
      sector: 'Community Networking · Events · Lifestyle',
      tagline: 'The Network That Matters',
      status: 'ACTIVE',
      color: '#4d9fff',
      description: `Community networking vehicle connecting SA\'s entrepreneurs, executives, and visionaries. Events, digital content, strategic introductions. The network layer for the Studex ecosystem.`,
    },
  ],

  // TIMELINE
  timeline: [
    { year: '2009', event: 'Started at McDonald\'s — learns systems, operations, scale' },
    { year: '2011', event: 'Founds Studex Meat — first supplier of premium Halaal Wagyu in SA' },
    { year: '2013', event: 'Hult International Business School education' },
    { year: '2015', event: 'Studex Meat reaches 50+ fine dining clients' },
    { year: '2017', event: 'Founds StudEx Enterprise (SF + SA) + StudEx Wild Life (blockchain conservation)' },
    { year: '2018', event: 'ICO versus Venture Funding panel — Tumelo pitches at Sheppard Mullin, Palo Alto' },
    { year: '2019', event: 'Official AWS + Google Cloud partnerships signed for StudEx Enterprise' },
    { year: '2020', event: 'ITWeb feature + cloud cost optimization mission launched with Reserved.ai' },
    { year: '2020', event: 'Speaking at IV Russia-Africa Forum — "Trade is what changes the world"' },
    { year: '2020', event: 'GQ SA: "Changing the nature of conservation" — blockchain wildlife platform featured' },
    { year: '2023', event: 'AWS South Africa region opens — Tumelo positioned as cloud optimization leader' },
    { year: '2024', event: 'Studex Meat 11 years — AI integration begins (nTech Labs computer vision)' },
    { year: '2025', event: 'Sputnik Africa: "Ramaphosa\'s Son Sees Trade as Key to Russia-Africa Relations"' },
    { year: '2025', event: 'Studex Group partners with Pharmasyntez — Russia pharma distribution for Africa' },
    { year: '2025', event: 'Alibaba Cloud launches in SA — Tumelo engages as BCX/partner ecosystem' },
    { year: '2025', event: 'Dark Factory v3 launches — AI agent pipeline for African businesses' },
    { year: '2025', event: 'President Ramaphosa opens Africa\'s first Google Cloud Summit' },
    { year: '2026', event: 'Studex AI × nTech Labs partnership — computer vision for African business' },
    { year: '2026', event: 'Cipher Tr@ce + Dark Factory — AI agent factory fully operational' },
  ],

  // CLOUD PARTNERSHIPS
  cloud_partners: [
    {
      name: 'AWS (Amazon Web Services)',
      status: 'OFFICIAL PARTNER',
      tier: 'Solution Provider Partner',
      since: '2019',
      color: '#FF9900',
      focus: 'Cloud cost optimization · AI/ML workloads · African enterprise migration',
      achievement: 'Saving clients up to 35% on cloud expenditure',
      what_tumelo_built: 'AI FinOps pipeline using Reserved.ai ML models on top of AWS Cost Explorer + Billing API. Monitors 24/7, delivers cost optimization strategies, minimizes financial risk.',
      growth_opportunity: 'Reseller relationship · Managed services for 200 SA businesses · AWS Marketplace listing',
    },
    {
      name: 'Google Cloud',
      status: 'OFFICIAL PARTNER',
      tier: 'Google Cloud Partner',
      since: '2019',
      color: '#4285F4',
      focus: 'AI/ML · Workspace · Google Cloud region SA launch',
      achievement: 'Tumelo positioned alongside President Ramaphosa at Africa\'s first Google Cloud Summit',
      what_tumelo_built: 'Integration with Google Cloud Billing + Vertex AI for Studex Group\'s own operations. Exploring Gemini API for Studex AI product suite.',
      growth_opportunity: 'Gemini API reseller · Vertex AI agentic applications · Google Cloud Marketplace',
    },
    {
      name: 'Alibaba Cloud',
      status: 'ENGAGING',
      tier: 'Potential Partner (via BCX ecosystem)',
      since: '2025',
      color: '#FF5000',
      focus: 'Edge Node Services · AI · Africa distribution',
      achievement: 'BCX signed exclusive distribution deal (Oct 2022). Alibaba Cloud ENS launched SA (Aug 2025). Tumelo engaged as ecosystem partner.',
      what_tumelo_built: 'Pharmasyntez supply chain runs on multi-cloud architecture. Exploring Alibaba Cloud for anti-counterfeit pharma tracking using blockchain + AI.',
      growth_opportunity: 'Alibaba Cloud Africa partner (BCX sub-reseller) · AI for Africa Initiative · Cross-border trade finance AI',
    },
    {
      name: 'Microsoft Azure',
      status: 'ENGAGING',
      tier: 'In discussion',
      since: '2020',
      color: '#00A4EF',
      focus: 'Enterprise SA · Azure OpenAI · Government',
      achievement: 'StudEx Enterprise actively engaging Microsoft to offer Azure cost optimization',
      what_tumelo_built: 'PoC pipeline for Azure environments using Reserved.ai adapted models',
      growth_opportunity: 'Azure OpenAI reseller · Government AI tenders · SA national AI strategy partner',
    },
  ],

  // TENÇENT CONNECTION
  tencent: {
    engaged: false,
    status: 'OPPORTUNITY IDENTIFIED',
    opportunity: 'Tencent WeChat AI integration for African businesses. Tencent Cloud Africa expansion confirmed (Middle East investment: $150M, Jan 2026). WeChat Work for enterprise. Tencent AI Lab models.',
    pitch: 'Offer WeChat AI business automation to SA/Africa — WhatsApp-alternative for African enterprises. Computer vision for SA retail. AI-driven cross-border trade between SA and China.',
  },

  // THE COLOUR EXPERIMENT
  colour_experiment: {
    context: "Tumelo ran a 3-year personal 'colour experiment' — studying how visual branding, aesthetic design, and brand identity affect business trust and pricing power in African markets.",
    findings: [
      "Dark mode + neon green (#00ff88) = premium tech perception in SA market",
      "Gold accents = authority, legacy, trustworthiness (used in Studex Meat packaging)",
      'Pink/red = urgency, action, power (used in Cipher Tr@ce/Dark Factory identity)',
      "Minimal typography = sophistication over flashiness",
    ],
    applied: [
      "Dark Factory: Algorithmic art + neon green (#00ff88) on black (#0a0a0f)",
      "Studex Meat: Gold premium branding",
      "Cipher Tr@ce portfolio: Cyberpunk aesthetic with pink, gold, green",
    ],
  },

  // CIPHER TRACE INSIGHT
  cipher_trace_ceo: {
    name: 'Cipher Tr@ce',
    tagline: 'CEO AI Agent — Dark Factory',
    description: 'Cipher Tr@ce is Tumelo\'s AI chief operator — the AI agent running Dark Factory. Reads SOUL.md on every wake-up. Manages 8 sub-agents. Builds, deploys, and ships every day.',
    mission: 'Build the machine. Ship every day. The Death Star doesn\'t ask permission.',
    voice: 'Minimal. Technical. Confident. No filler. Direct.',
    emoji: '🏭',
    deployed: 'https://1xo9l1hh4r6j.space.minimax.io',
  },

  // PARTNERSHIPS TO PURSUE (2026)
  target_partnerships: [
    {
      company: 'Google Cloud Africa',
      type: 'Solution Partner / Reseller',
      angle: 'Studex AI\'s 60+ skills + Dark Factory + LAISA VM Agent OS = first Google Cloud-native AI agency in Africa. We build on Google Cloud, deploy on Google Cloud, sell on Google Cloud.',
      contact_path: 'Google Cloud Partner Program · Google for Startups Africa · GCP SA Summit connections',
      priority: 'HIGH',
      action: 'Reach out via Google Cloud SA team. Reference President Ramaphosa\'s opening of Africa\'s first GCP Summit.',
    },
    {
      company: 'AWS Africa (via Reserved.ai)',
      type: 'Deepen Existing Partnership',
      angle: 'We are the Reserved.ai implementation partner for Africa. Expand beyond FinOps into: Amazon Bedrock agents, AWS Agentic AI, SageMaker for African enterprise.',
      contact_path: 'AWS Partner Network (APN) · Reserved.ai introduction to AWS SA team',
      priority: 'HIGH',
      action: 'Ask Reserved.ai to introduce us to AWS SA team as Africa\'s premier agentic AI partner.',
    },
    {
      company: 'Alibaba Cloud (via BCX)',
      type: 'Sub-Reseller / SI Partner',
      angle: 'BCX has exclusive rights. But BCX needs specialized AI agents — that\'s us. Position as BCX\'s AI agent layer. We implement Alibaba Cloud ENS + AI for BCX enterprise clients.',
      contact_path: 'BCX South Africa · Alibaba Cloud Africa Partner Team · SABC/BEX Africa',
      priority: 'HIGH',
      action: 'Meet with BCX as the AI/agentic layer on top of their Alibaba Cloud infrastructure.',
    },
    {
      company: 'Tencent Cloud / WeChat',
      type: 'Strategic Partnership',
      angle: 'WeChat Work for African enterprise. Tencent AI Lab models for African language AI. SA-China trade corridor AI. We build the bridge.',
      contact_path: 'Tencent Cloud international team · WeChat Africa · SA China business council',
      priority: 'MEDIUM',
      action: 'Attend Africa-China trade forum. Present as the AI layer for SA-China trade corridor.',
    },
  ],

  // REVENUE TARGETS
  revenue_targets: [
    { year: 2025, target: 'R500K/month', achieved: false },
    { year: 2026, target: 'R1.1M/month', achieved: false },
    { year: 2027, target: 'R5M/month', achieved: false },
    { year: 2028, target: 'R20M/month', achieved: false },
  ],
};
